#! /bin/bash

echo "Installing stuff"
parts install php5 php5-apache2 mysql

echo "starting things"
echo "parts start apache2 mysql" > ~/startup.sh
chmod +x ~/startup.sh
~/startup.sh

pass=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
mysql -u root -e"create database codio; create user codio@localhost identified by '$pass'; grant usage on *.* to codio@localhost; grant all privileges on codio.* to codio@localhost"

echo "=============================="
echo "db credentials are as follows:"
echo ""
echo "user: codio"
echo "pass: $pass"
echo "db: codio"
echo ""
echo "=============================="

echo ""
echo "finishing up"

echo "// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', 'codio');

/** MySQL database username */
define('DB_USER', 'codio');

/** MySQL database password */
define('DB_PASSWORD', $pass);

/** MySQL hostname */
define('DB_HOST', 'localhost');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');
" > ~/workspace/wp-config-local.php

echo "all done"